// load data from data file generated by Yahoo! YCSB
// data load for op - key - field dataset
void loadData(string file){
    ifstream fin(file);
    string op, key, field;
    while(fin >> op >> key >> field){
        char value[VALUE_SIZE+128];
        fin.read(value, 1);
        fin.getline(value, VALUE_SIZE+128, '\n');
    }
    fin.close();
}
// data load for key-value dataset
void loadOperation(string file, T& hashTable){
    ifstream fin(file);
    string op, key;
    while(fin >> op >> key)
        readSequence.push_back(key);
    fin.close();
}

int main() {
s
    return 0;
}
